name: events-workflow
on:
  push:   
  schedule:
    - cron : '0 * * * *'

jobs:
  code_base:
    name: code base
    runs-on: ubuntu-latest
    steps: 
      - name: Print msg
        run : echo "Hello world!"
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Print msg with event name
        run : echo "The job was triggered by a ${{github.event_name}} event." 
      - name: Run Bash script       
        shell: bash
        run: |
             count=$(ls -1 . | wc -l) | 
             echo "O diretório contém $count arquivos."
        